
import type { Metadata } from "next";
import "./globals.css";
import LayoutContent from "@/components/layout/LayoutContent";
import { Lora, Playfair_Display } from 'next/font/google';
import { ReactNode } from "react";
import { AuthProvider } from "@/hooks/AuthContext";
import { GuestProvider } from "@/hooks/GuestContext";
import { ProductProvider } from "@/hooks/ProductContext";

// Configure your fonts
const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-playfair',
});

const lora = Lora({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700'],
  variable: '--font-lora',
});

export const metadata: Metadata = {
  title: "Alibaba FullStack",
  description: "Generated by create next app",
};

// This is a Client Component because it uses `usePathname`
export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${lora.variable} bg-[#f7fafc]`}
      >
        <AuthProvider>
          <GuestProvider>
            <ProductProvider>
            <LayoutContent>{children}</LayoutContent>
            </ProductProvider>
          </GuestProvider>
        </AuthProvider>
      </body>
    </html>
  );
}